function [result] = normalise(histograms, event_counter)
%NORMALISE 
% A characteristic of event-based sensors is that the amount
% of events generated by a moving object is proportional to its
% contrast: higher contrast objects generate more events than
% low contrast objects. To make the cell descriptor more invariant 
% to contrast, we therefore normalize h by the number of events |C| 
% contained in the spatio-temporal window used to compute it. 
% 基于事件的传感器的特征在于，移动物体产生的事件数量与其对比度成正比：
% 对比度较高的物体比对比度较低的物体产生的事件更多。 
% 为了使单元描述符对对比度更加不变，
% 因此，我们根据事件数| C |对h进行归一化。 
% 包含在用于计算时空的窗口中。

result  = zeros(size(histograms));
        
% normalise 归一化
    for i  = 1: size(histograms,1)
        for p  = 1:size(histograms,2)
            result(i,p,:,:) = histograms(i,p,:,:)./(event_counter(i,p)+0.1);
        end
    end
end

